{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tiamat/2.1.0-1.8.2/tiamat-2.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "tiamat",
    "version": "2.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-wasm-js-2.1.0-1.8.2.klib",
          "url": "tiamat-wasm-js-2.1.0-1.8.2.klib",
          "size": 149967,
          "sha512": "99302c38097afa83fb0fa603abc75620dae8ebaaf27c4dd8224eb0e50530b0dbe510fe74ac95c05f7e3da4a9593491ce158e043f02f849646fb224f5387a9793",
          "sha256": "9dfe85dac81cc6ccc25322148df22087615baf3b9bea13a58f9e4f5ed598b2ad",
          "sha1": "ad085fa5e31527f9e1456d4e97b9f48adfc9c761",
          "md5": "2c6584d6f921dc8b79e5c0de70efc894"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-wasm-js-2.1.0-1.8.2.klib",
          "url": "tiamat-wasm-js-2.1.0-1.8.2.klib",
          "size": 149967,
          "sha512": "99302c38097afa83fb0fa603abc75620dae8ebaaf27c4dd8224eb0e50530b0dbe510fe74ac95c05f7e3da4a9593491ce158e043f02f849646fb224f5387a9793",
          "sha256": "9dfe85dac81cc6ccc25322148df22087615baf3b9bea13a58f9e4f5ed598b2ad",
          "sha1": "ad085fa5e31527f9e1456d4e97b9f48adfc9c761",
          "md5": "2c6584d6f921dc8b79e5c0de70efc894"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "tiamat-wasm-js-2.1.0-1.8.2-sources.jar",
          "url": "tiamat-wasm-js-2.1.0-1.8.2-sources.jar",
          "size": 28392,
          "sha512": "e2e86c10dec40332e5adcf342d5d091c7b69cde360393911302d32ddab41666a39a8ca59cf65b0ddcd1fce674a2a1df5cd82fddb8da23bf9f0de0ed31c742a6c",
          "sha256": "e1a994573bd9efa20387d1bdde3326565764e33cc2f3c76f4a319526b59a8cc0",
          "sha1": "1ce0f3356c9b13e0c3bca2381b3c3522f11d35ae",
          "md5": "68b8dcddda3fae768efe10f192a225c5"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-2.1.0-1.8.2.kotlin_resources.zip",
          "url": "tiamat-wasm-js-2.1.0-1.8.2-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "f1539357fd23d8a6f7a22f2e4e3becd83aad57b27bb0ee5eaa99a27b5fd98e086a23b0869b149b4a5805b412e324196cd769a8018a927ebc708343d9e7f01f84",
          "sha256": "4c1ec0126410731236630ff06e38bf96ed7d77389093d34f6f08ea91350ed056",
          "sha1": "ef947fc47b302b340b3a495e9efebabc13b5e28d",
          "md5": "03869e57d8b4bb0ae2c3630ca807b4b6"
        }
      ]
    }
  ]
}
