# Release template for GitHub Releases

changelog:
  categories:
    - title: ✨ Features
      labels:
        - feature
    - title: 🐛 Bugfixes
      labels:
        - bug-fix
    - title: 🧹 Housekeeping
      labels:
        - housekeeping
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: ✏️ Others
      labels:
        - '*'
      exclude:
        labels:
          - feature
          - bug-fix
          - housekeeping
          - dependencies
