# Release template for GitHub Releases

changelog:
  categories:
    - title: 🖥️✨ CLI features
      labels:
        - feature-cli
    - title: 🖥️🐛 CLI bugfixes
      labels:
        - bugfix-cli
    - title: 🔌✨ Plugin features
      labels:
        - feature-plugin
    - title: 🔌🐛 Plugin bugfixes
      labels:
        - bugfix-plugin
    - title: ✨ Features
      labels:
        - feature
    - title: 🐛 Bugfixes
      labels:
        - bugfix
    - title: 🧹 Housekeeping
      labels:
        - housekeeping
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: ✏️ Others
      labels:
        - '*'
      exclude:
        labels:
          - bugfix-cli
          - bugfix-plugin
          - bugfix
          - feature-cli
          - feature-plugin
          - feature
          - housekeeping
          - dependencies
          - changelog
