# Release template for GitHub Releases

changelog:
  categories:
    - title: 🖥️✨ CLI features
      labels:
        - feature-cli
    - title: 🖥️🐛 CLI bugfixes
      labels:
        - bugfix-cli
    - title: 🔌✨ IntelliJ Plugin features
      labels:
        - feature-intellij-plugin
    - title: 🔌🐛 IntelliJ Plugin bugfixes
      labels:
        - bugfix-intellij-plugin
    - title: 🐘✨ Gradle Plugin features
      labels:
        - feature-gradle-plugin
    - title: 🐘🐛 Gradle Plugin bugfixes
      labels:
        - bugfix-gradle-plugin
    - title: ✨ SDK Features
      labels:
        - feature-sdk
    - title: 🧩🐛 SDK Bugfixes
      labels:
        - bugfix-sdk
    - title: 🧹 Housekeeping
      labels:
        - housekeeping
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: ✏️ Others
      labels:
        - '*'
      exclude:
        labels:
          - bugfix-cli
          - bugfix-gradle-plugin
          - bugfix-intellij-plugin
          - bugfix-sdk
          - feature-cli
          - feature-gradle-plugin
          - feature-intellij-plugin
          - feature-sdk
          - housekeeping
          - dependencies
          - changelog
