{
  "formatVersion": "1.1",
  "component": {
    "url": "../../leviathan/3.1.0-1.8.2/leviathan-3.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "leviathan",
    "version": "3.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-iosSimulatorArm64Main-3.1.0-1.8.2.klib",
          "url": "leviathan-iossimulatorarm64-3.1.0-1.8.2.klib",
          "size": 13850,
          "sha512": "96ed702d2a3f4cbb56ed5ef6b7d80b9abc6715fd7da6884064ae9194240d21a1587b19581716d9d10ab350812354c541e6ae359148a158e1901939c5fe9e18e1",
          "sha256": "82fc82f15d91e2d9da1ecd951ddc0d0961a60df4c088fad9e2cb89d316df370a",
          "sha1": "bff55faf262432da36bbb28d5bbbe55818f095e1",
          "md5": "77f7f943c4b31d8684275b4e6d2e9f79"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "leviathan-iossimulatorarm64-3.1.0-1.8.2-sources.jar",
          "url": "leviathan-iossimulatorarm64-3.1.0-1.8.2-sources.jar",
          "size": 2790,
          "sha512": "1303aadf798b6073ff218b7266da7912708b3372d3a4582915a3e239a039dbccd3cbb74ec5a58d30002999dd7ec1a12826b22e8967fc0496e3fa9a3f6ec62519",
          "sha256": "bf95d41c29ef7307f7832a581d2eb65f4cf604b3fb29ac911641dafc5d763759",
          "sha1": "43e1dbead9322d5b23848d7a555f38c0c3487a75",
          "md5": "ed495bed930834c8335c5a372daefdd3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-iossimulatorarm64-3.1.0-1.8.2-metadata.jar",
          "url": "leviathan-iossimulatorarm64-3.1.0-1.8.2-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
