{
  "formatVersion": "1.1",
  "component": {
    "url": "../../leviathan-compose/3.1.0-1.8.2/leviathan-compose-3.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "leviathan-compose",
    "version": "3.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose-wasm-js-3.1.0-1.8.2.klib",
          "url": "leviathan-compose-wasm-js-3.1.0-1.8.2.klib",
          "size": 8407,
          "sha512": "db60f2153189d40dd6627d8545fbd22a38c913e3ccef403f9fb4b19b82bed7c34307ba67af00bfa283a4e0d938b2123c7be78a6cb83d4bf48369495f88ed442c",
          "sha256": "ec53d697ff106f95691fb867332154593267ecf5eb68f8cf6caabe8f07488072",
          "sha1": "138e35f3d00d83ddb445ef6810ba1558b3cf0bde",
          "md5": "c3f44e5339447f5722f04b18a86c5266"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose-wasm-js-3.1.0-1.8.2.klib",
          "url": "leviathan-compose-wasm-js-3.1.0-1.8.2.klib",
          "size": 8407,
          "sha512": "db60f2153189d40dd6627d8545fbd22a38c913e3ccef403f9fb4b19b82bed7c34307ba67af00bfa283a4e0d938b2123c7be78a6cb83d4bf48369495f88ed442c",
          "sha256": "ec53d697ff106f95691fb867332154593267ecf5eb68f8cf6caabe8f07488072",
          "sha1": "138e35f3d00d83ddb445ef6810ba1558b3cf0bde",
          "md5": "c3f44e5339447f5722f04b18a86c5266"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "leviathan-compose-wasm-js-3.1.0-1.8.2-sources.jar",
          "url": "leviathan-compose-wasm-js-3.1.0-1.8.2-sources.jar",
          "size": 1588,
          "sha512": "23de181f020f834e30f9f92191bd6cf9a8c91c47e5ff9948eb49edce313619fabe2575ed7a89ad5a230266a82806d5c70f81f1ebe8348af7102be89bbe53e17d",
          "sha256": "91f55d91e3ceb57b6e26300fa395098ff97ea9f7a84891926839837cd4240836",
          "sha1": "6b47ed0560ba0597dbb81460f1e66bf28926caa7",
          "md5": "97f546b54d1656117b8189160667ff39"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose-3.1.0-1.8.2.kotlin_resources.zip",
          "url": "leviathan-compose-wasm-js-3.1.0-1.8.2-kotlin_resources.kotlin_resources.zip",
          "size": 368,
          "sha512": "6512964b107b782151e24b99eb1915e6527ea879d027e50fd706ba661d2c0fce121bc9058a880c10369dd104b5f619ceab0a63389a343eb43d0b22a8d6687a54",
          "sha256": "91702cbb78a00ead068427c16664ba2958c3889d91cbd732de8c14c258a946d2",
          "sha1": "81b51b56a27c79085b2dc2757901153b9d3536ec",
          "md5": "3bb77e22a41a826a32c4751531dc5c3a"
        }
      ]
    }
  ]
}
