name: 'Sign and Verify IntelliJ Plugin'
description: 'A composite actions for signing and verifying IntelliJ plugins.'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build signed plugin
      shell: bash
      run: ./gradlew signPlugin
    - name: Verify IntelliJ plugin
      # https://www.jetbrains.com/idea/download/other.html
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v2.0.2
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        plugin-location: idea-plugin/build/distributions/*-signed.zip
        ide-versions: |
          ideaIC:2024.1
          ideaIC:2024.1.1
          ideaIC:2024.1.2
          ideaIC:2024.1.3
          ideaIC:2024.1.4
          ideaIC:LATEST-EAP-SNAPSHOT
        failure-levels: |
          COMPATIBILITY_WARNINGS
          COMPATIBILITY_PROBLEMS
          DEPRECATED_API_USAGES
          INTERNAL_API_USAGES
          OVERRIDE_ONLY_API_USAGES
          NON_EXTENDABLE_API_USAGES
          PLUGIN_STRUCTURE_WARNINGS
          MISSING_DEPENDENCIES
          INVALID_PLUGIN
          NOT_DYNAMIC
