{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.composegears",
    "module": "tiamat",
    "version": "2.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-metadata-2.1.0-1.8.2.jar",
          "url": "tiamat-2.1.0-1.8.2.jar",
          "size": 19795,
          "sha512": "821428ea79e3bf7cad013d8ca22b9bc64c6165a505895767fc0d7ec73cb3c1e74494bc9d4ac503759b95befcb85016ef4b002ae5d8193c35f07a6f0c70e98b37",
          "sha256": "813538c57431d23d12651ba4ba5c86b6b0d38bce2ca2e6d0e3bacd427f609d78",
          "sha1": "6cc0ca5ee419ad8ce9f5c0e4e59e0f37361d4fc5",
          "md5": "03a540f7ec601e9840c9597eddbff142"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "tiamat-kotlin-2.1.0-1.8.2-sources.jar",
          "url": "tiamat-2.1.0-1.8.2-sources.jar",
          "size": 28548,
          "sha512": "6ce895f1d32bd1e1f1e95534e58d214cd0e31f6074a5a3b4857aef3f2956ce5890da197a78a36b8dc7f95e2f9a3d5796aaaec6738292d2c32cf839ef77446f5d",
          "sha256": "a2d4680dc3dedc909732380393673a745bd91d9054b412addd467ebfc81cfdd3",
          "sha1": "cf77b81e3cf3009899355ac6200ad0e747c482c0",
          "md5": "8997b522b710baf0c68a6853076aea97"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tiamat-android/2.1.0-1.8.2/tiamat-android-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-android",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tiamat-android/2.1.0-1.8.2/tiamat-android-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-android",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tiamat-android/2.1.0-1.8.2/tiamat-android-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-android",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosarm64/2.1.0-1.8.2/tiamat-iosarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosarm64/2.1.0-1.8.2/tiamat-iosarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosarm64/2.1.0-1.8.2/tiamat-iosarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosarm64/2.1.0-1.8.2/tiamat-iosarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iossimulatorarm64/2.1.0-1.8.2/tiamat-iossimulatorarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iossimulatorarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iossimulatorarm64/2.1.0-1.8.2/tiamat-iossimulatorarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iossimulatorarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iossimulatorarm64/2.1.0-1.8.2/tiamat-iossimulatorarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iossimulatorarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iossimulatorarm64/2.1.0-1.8.2/tiamat-iossimulatorarm64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iossimulatorarm64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosx64/2.1.0-1.8.2/tiamat-iosx64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosx64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosx64/2.1.0-1.8.2/tiamat-iosx64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosx64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosx64/2.1.0-1.8.2/tiamat-iosx64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosx64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../tiamat-iosx64/2.1.0-1.8.2/tiamat-iosx64-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-iosx64",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tiamat-jvm/2.1.0-1.8.2/tiamat-jvm-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-jvm",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tiamat-jvm/2.1.0-1.8.2/tiamat-jvm-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-jvm",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../tiamat-jvm/2.1.0-1.8.2/tiamat-jvm-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-jvm",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../tiamat-wasm-js/2.1.0-1.8.2/tiamat-wasm-js-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-wasm-js",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../tiamat-wasm-js/2.1.0-1.8.2/tiamat-wasm-js-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-wasm-js",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../tiamat-wasm-js/2.1.0-1.8.2/tiamat-wasm-js-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-wasm-js",
        "version": "2.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../tiamat-wasm-js/2.1.0-1.8.2/tiamat-wasm-js-2.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "tiamat-wasm-js",
        "version": "2.1.0-1.8.2"
      }
    }
  ]
}
