name: Setup Java
description: Setup Java 25
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
