{
  "formatVersion": "1.1",
  "component": {
    "url": "../../leviathan-compose/3.1.0-1.8.2/leviathan-compose-3.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "leviathan-compose",
    "version": "3.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose.aar",
          "url": "leviathan-compose-android-3.1.0-1.8.2.aar",
          "size": 6452,
          "sha512": "5c29d2d1db81cac2cfd2d9a7e652a5adc702f4fd566907803986aae71542f0b18e0a0c75ea94518cfa6482fab78a3da943371768ad5878eecf77e055fdb7df70",
          "sha256": "fe9fc24827f6f10fe9b602f2d23c56078bfc67ffb34c9c03ba00646ab7ec2c19",
          "sha1": "059ff3ced204bbecf426c1abec5b37c328b2f2ef",
          "md5": "54c99526c7ec5a526a1ff3fbb83ceae9"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose.aar",
          "url": "leviathan-compose-android-3.1.0-1.8.2.aar",
          "size": 6452,
          "sha512": "5c29d2d1db81cac2cfd2d9a7e652a5adc702f4fd566907803986aae71542f0b18e0a0c75ea94518cfa6482fab78a3da943371768ad5878eecf77e055fdb7df70",
          "sha256": "fe9fc24827f6f10fe9b602f2d23c56078bfc67ffb34c9c03ba00646ab7ec2c19",
          "sha1": "059ff3ced204bbecf426c1abec5b37c328b2f2ef",
          "md5": "54c99526c7ec5a526a1ff3fbb83ceae9"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "leviathan-compose-android-3.1.0-1.8.2-sources.jar",
          "url": "leviathan-compose-android-3.1.0-1.8.2-sources.jar",
          "size": 1588,
          "sha512": "23de181f020f834e30f9f92191bd6cf9a8c91c47e5ff9948eb49edce313619fabe2575ed7a89ad5a230266a82806d5c70f81f1ebe8348af7102be89bbe53e17d",
          "sha256": "91f55d91e3ceb57b6e26300fa395098ff97ea9f7a84891926839837cd4240836",
          "sha1": "6b47ed0560ba0597dbb81460f1e66bf28926caa7",
          "md5": "97f546b54d1656117b8189160667ff39"
        }
      ]
    }
  ]
}
