{
  "formatVersion": "1.1",
  "component": {
    "url": "../../leviathan/2.0.0/leviathan-2.0.0.module",
    "group": "io.github.composegears",
    "module": "leviathan",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-release.aar",
          "url": "leviathan-android-2.0.0.aar",
          "size": 15092,
          "sha512": "6507529a22e5894b2e2bc499159ac8eda60dae5d2734921f278bc44208b9d267ed15a0ba27ae78fae9a118b31dbd6a828b6fd360fa9e0ee88778cc26b2375ca2",
          "sha256": "8270f110b6f846881f25d757aafa34e6387f3620da142e9aef4ded1a3052138b",
          "sha1": "1b82de4d4d1f546e99e79e9102d798372a5d8f7d",
          "md5": "151ba1a5be5291c9db7b2b46663bca74"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "leviathan-release.aar",
          "url": "leviathan-android-2.0.0.aar",
          "size": 15092,
          "sha512": "6507529a22e5894b2e2bc499159ac8eda60dae5d2734921f278bc44208b9d267ed15a0ba27ae78fae9a118b31dbd6a828b6fd360fa9e0ee88778cc26b2375ca2",
          "sha256": "8270f110b6f846881f25d757aafa34e6387f3620da142e9aef4ded1a3052138b",
          "sha1": "1b82de4d4d1f546e99e79e9102d798372a5d8f7d",
          "md5": "151ba1a5be5291c9db7b2b46663bca74"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "leviathan-android-2.0.0-sources.jar",
          "url": "leviathan-android-2.0.0-sources.jar",
          "size": 2105,
          "sha512": "1024829a1304572f5e52baa3c1204f8198b55fec4ae1745d04906b6099e75de3f2f714a11befb56d5ba04d7894d4e7628ea9b788c7965600a1829765b71fedf6",
          "sha256": "509e2c6abc941f38c065811fc530ff761ac6232eea1a9af2cbec5e7ddd69537f",
          "sha1": "0b8f83a8d8d87f7c573dcddad8a78b7392f7572f",
          "md5": "054c282ecd2fcdc12b4be264c7b8f498"
        }
      ]
    }
  ]
}
