package io.github.composegears.valkyrie.parser.kmp.xml

import io.github.composegears.valkyrie.sdk.ir.core.IrColor

private const val ANDROID_COLOR_PREFIX = "@android:color/"

internal object AndroidColorParser {

    fun parse(value: String): IrColor? {
        return androidColorsMap[value.substringAfter(ANDROID_COLOR_PREFIX)]
            ?.let { IrColor(it) }
    }

    // NOTE: Taken from https://gist.github.com/sghael/2930380
    val androidColorsMap = mapOf(
        "white" to "#FFFFFF",
        "ivory" to "#FFFFF0",
        "light_yellow" to "#FFFFE0",
        "yellow" to "#FFFF00",
        "snow" to "#FFFAFA",
        "floral_white" to "#FFFAF0",
        "lemon_chiffon" to "#FFFACD",
        "cornsilk" to "#FFF8DC",
        "seashell" to "#FFF5EE",
        "lavender_blush" to "#FFF0F5",
        "papaya_whip" to "#FFEFD5",
        "blanched_almond" to "#FFEBCD",
        "misty_rose" to "#FFE4E1",
        "bisque" to "#FFE4C4",
        "moccasin" to "#FFE4B5",
        "navajo_white" to "#FFDEAD",
        "peach_puff" to "#FFDAB9",
        "cold" to "#FFD700",
        "pink" to "#FFC0CB",
        "light_pink" to "#FFB6C1",
        "orange" to "#FFA500",
        "light_salmon" to "#FFA07A",
        "dark_orange" to "#FF8C00",
        "coral" to "#FF7F50",
        "hot_pink" to "#FF69B4",
        "tomato" to "#FF6347",
        "orange_red" to "#FF4500",
        "deep_pink" to "#FF1493",
        "fuchsia" to "#FF00FF",
        "magenta" to "#FF00FF",
        "red" to "#FF0000",
        "old_lace" to "#FDF5E6",
        "light_goldenrod_yellow" to "#FAFAD2",
        "linen" to "#FAF0E6",
        "antique_white" to "#FAEBD7",
        "salmon" to "#FA8072",
        "ghost_white" to "#F8F8FF",
        "mint_cream" to "#F5FFFA",
        "white_smoke" to "#F5F5F5",
        "beige" to "#F5F5DC",
        "wheat" to "#F5DEB3",
        "sandy_brown" to "#F4A460",
        "azure" to "#F0FFFF",
        "honeydew" to "#F0FFF0",
        "alice_blue" to "#F0F8FF",
        "khaki" to "#F0E68C",
        "light_coral" to "#F08080",
        "pale_goldenrod" to "#EEE8AA",
        "violet" to "#EE82EE",
        "dark_salmon" to "#E9967A",
        "lavender" to "#E6E6FA",
        "light_cyan" to "#E0FFFF",
        "burlyWood" to "#DEB887",
        "plum" to "#DDA0DD",
        "gainsboro" to "#DCDCDC",
        "crimson" to "#DC143C",
        "pale_violet_red" to "#DB7093",
        "goldenrod" to "#DAA520",
        "orchid" to "#DA70D6",
        "thistle" to "#D8BFD8",
        "light_grey" to "#D3D3D3",
        "tan" to "#D2B48C",
        "chocolate" to "#D2691E",
        "peru" to "#CD853F",
        "indian_red" to "#CD5C5C",
        "medium_violet_red" to "#C71585",
        "silver" to "#C0C0C0",
        "dark_khaki" to "#BDB76B",
        "rosy_brown" to "#BC8F8F",
        "medium_orchid" to "#BA55D3",
        "dark_goldenrod" to "#B8860B",
        "fire_brick" to "#B22222",
        "powder_blue" to "#B0E0E6",
        "light_steel_blue" to "#B0C4DE",
        "pale_turquoise" to "#AFEEEE",
        "greenYellow" to "#ADFF2F",
        "light_blue" to "#ADD8E6",
        "dark_gray" to "#A9A9A9",
        "brown" to "#A52A2A",
        "sienna" to "#A0522D",
        "yellow_green" to "#9ACD32",
        "dark_orchid" to "#9932CC",
        "pale_green" to "#98FB98",
        "dark_violet" to "#9400D3",
        "mediumPurple" to "#9370DB",
        "_light_green" to "#90EE90",
        "dark_sea_green" to "#8FBC8F",
        "saddle_brown" to "#8B4513",
        "dark_magenta" to "#8B008B",
        "dark_red" to "#8B0000",
        "blue_violet" to "#8A2BE2",
        "light_sky_blue" to "#87CEFA",
        "sky_blue" to "#87CEEB",
        "gray" to "#808080",
        "olive" to "#808000",
        "purple" to "#800080",
        "maroon" to "#800000",
        "aquamarine" to "#7FFFD4",
        "chartreuse" to "#7FFF00",
        "lawn_green" to "#7CFC00",
        "medium_slate_blue" to "#7B68EE",
        "light_slate_gray" to "#778899",
        "slate_gray" to "#708090",
        "olive_drab" to "#6B8E23",
        "slate_blue" to "#6A5ACD",
        "dim_gray" to "#696969",
        "medium_aquamarine" to "#66CDAA",
        "cornflower_blue" to "#6495ED",
        "cadet_blue" to "#5F9EA0",
        "dark_olive_green" to "#556B2F",
        "indigo" to "#4B0082",
        "medium_turquoise" to "#48D1CC",
        "dark_slate_blue" to "#483D8B",
        "steel_blue" to "#4682B4",
        "royal_blue" to "#4169E1",
        "turquoise" to "#40E0D0",
        "medium_sea_green" to "#3CB371",
        "lime_green" to "#32CD32",
        "dark_slate_gray" to "#2F4F4F",
        "sea_green" to "#2E8B57",
        "forest_green" to "#228B22",
        "light_sea_green" to "#20B2AA",
        "dodger_blue" to "#1E90FF",
        "midnight_blue" to "#191970",
        "aqua" to "#00FFFF",
        "cyan" to "#00FFFF",
        "spring_green" to "#00FF7F",
        "lime" to "#00FF00",
        "medium_spring_green" to "#00FA9A",
        "dark_turquoise" to "#00CED1",
        "deep_sky_blue" to "#00BFFF",
        "dark_cyan" to "#008B8B",
        "teal" to "#008080",
        "green" to "#008000",
        "dark_green" to "#006400",
        "blue" to "#0000FF",
        "medium_blue" to "#0000CD",
        "dark_blue" to "#00008B",
        "navy" to "#000080",
        "black" to "#000000",
    )
}
