{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tiamat/2.1.0-1.8.2/tiamat-2.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "tiamat",
    "version": "2.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat.aar",
          "url": "tiamat-android-2.1.0-1.8.2.aar",
          "size": 139250,
          "sha512": "bff21bb56bc0feaf1944ded3d6ce8e5980bd0fd9be2246d0591cd11e662ab1c0505d90dafad68ff7a5e530d6db82ca7cafcacd26ee94cad96ec04b45d55c6589",
          "sha256": "fd105a2a88a513bd82f2243e8716115d2d3eede40d6803a67bc3b73cfab38e00",
          "sha1": "55f0e3c3d6319a7eff1b13d4a771eeb318ee6390",
          "md5": "161a53fcfdad898f98325042847e06d9"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat.aar",
          "url": "tiamat-android-2.1.0-1.8.2.aar",
          "size": 139250,
          "sha512": "bff21bb56bc0feaf1944ded3d6ce8e5980bd0fd9be2246d0591cd11e662ab1c0505d90dafad68ff7a5e530d6db82ca7cafcacd26ee94cad96ec04b45d55c6589",
          "sha256": "fd105a2a88a513bd82f2243e8716115d2d3eede40d6803a67bc3b73cfab38e00",
          "sha1": "55f0e3c3d6319a7eff1b13d4a771eeb318ee6390",
          "md5": "161a53fcfdad898f98325042847e06d9"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tiamat-android-2.1.0-1.8.2-sources.jar",
          "url": "tiamat-android-2.1.0-1.8.2-sources.jar",
          "size": 28597,
          "sha512": "70e9a8bfbd4e296b524eedad8d3b27321e6a91dde522c05ea3c7be7d941b86476522ee3baf215adddcc926058283c8179cf58830de4ff644d9ac7f7bfbeee25c",
          "sha256": "0cf2e6e3ae16ded0adb32d47cbc5d82046811cefbb6a200e1477a37228df950a",
          "sha1": "0fad70fcc503c84b9f1bd7b1c177fff1f006f44d",
          "md5": "6319651408b704792efa82ef2c13650b"
        }
      ]
    }
  ]
}
