{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tiamat/2.1.0-1.8.2/tiamat-2.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "tiamat",
    "version": "2.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-iosSimulatorArm64Main-2.1.0-1.8.2.klib",
          "url": "tiamat-iossimulatorarm64-2.1.0-1.8.2.klib",
          "size": 158588,
          "sha512": "ad2e65f52710ae19f0cbce1bcc1584ae90b2d60dcd1c29abd46decc57844bb559e306b01feaf3fc34f1206768709ddb6049195eb805fb14ef098bd061daca3b5",
          "sha256": "6bcf59b0b300f8123925fcc8e80a9a4504b0f13b8418d25ca48ae2d1fb34cf0c",
          "sha1": "b7a5799a3b71916ceed30c15541b8c4d34d40881",
          "md5": "d9394b0b15553d606759297bb3e2e383"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "tiamat-iossimulatorarm64-2.1.0-1.8.2-sources.jar",
          "url": "tiamat-iossimulatorarm64-2.1.0-1.8.2-sources.jar",
          "size": 28548,
          "sha512": "74c4a3a07239c6d40b6e23a0cc09dfbc464766c6dfab94f3b66d2d3f31823fc2a8696015e15584749540725eb2ce16fcfb89863f0866887ad03e2bb17955302b",
          "sha256": "548d934e1b8fae18d11a9f0b1a297f34d22d0b25cf9ad942cf623602a3cd2f3f",
          "sha1": "32b2ad5a9a55cedd9d9b491cb081f60e71535c69",
          "md5": "72d6534383a30e4a458e10ccaa175e8c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-2.1.0-1.8.2.kotlin_resources.zip",
          "url": "tiamat-iossimulatorarm64-2.1.0-1.8.2-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "f1539357fd23d8a6f7a22f2e4e3becd83aad57b27bb0ee5eaa99a27b5fd98e086a23b0869b149b4a5805b412e324196cd769a8018a927ebc708343d9e7f01f84",
          "sha256": "4c1ec0126410731236630ff06e38bf96ed7d77389093d34f6f08ea91350ed056",
          "sha1": "ef947fc47b302b340b3a495e9efebabc13b5e28d",
          "md5": "03869e57d8b4bb0ae2c3630ca807b4b6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "tiamat-iossimulatorarm64-2.1.0-1.8.2-metadata.jar",
          "url": "tiamat-iossimulatorarm64-2.1.0-1.8.2-metadata.jar",
          "size": 2463,
          "sha512": "743fdc8e1e9a65d0ce3b59e00d52ae3fb66bae84254bd9fd74cd4aaef4f7deb54b17ed4f8fc69b2935ccd0442f1a68ed51b20dfe1869656c157e647b7bff95bb",
          "sha256": "561ca1add567346219bbc5d8c0d79b8882a70665b5314458ac7e7c695dda3bf0",
          "sha1": "81a40ab3acca0c5481d3e19158d3660e1843a108",
          "md5": "0df00b7a908cb977e9f6a013a6e13fe0"
        }
      ]
    }
  ]
}
