{
  "formatVersion": "1.1",
  "component": {
    "url": "../../leviathan-compose/3.1.0-1.8.2/leviathan-compose-3.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "leviathan-compose",
    "version": "3.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose-jvm-3.1.0-1.8.2.jar",
          "url": "leviathan-compose-jvm-3.1.0-1.8.2.jar",
          "size": 7280,
          "sha512": "7d1c4d7a49fd383070582df6e0a2a9ceb23ef5311153c83eadfd19f33485ea679588f3aa002d1e82d39ea21a85b436d6edc1abc259345d68ddbb63bc55e4f00c",
          "sha256": "1ad0d5bf922721f147cd22af59f757e08728da1070c4c1e23793865652b4fe4e",
          "sha1": "350fc098e74a64fad2fb0ab3088dc30ab70b3284",
          "md5": "4789d0918e3c179069233416ae76449d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose-jvm-3.1.0-1.8.2.jar",
          "url": "leviathan-compose-jvm-3.1.0-1.8.2.jar",
          "size": 7280,
          "sha512": "7d1c4d7a49fd383070582df6e0a2a9ceb23ef5311153c83eadfd19f33485ea679588f3aa002d1e82d39ea21a85b436d6edc1abc259345d68ddbb63bc55e4f00c",
          "sha256": "1ad0d5bf922721f147cd22af59f757e08728da1070c4c1e23793865652b4fe4e",
          "sha1": "350fc098e74a64fad2fb0ab3088dc30ab70b3284",
          "md5": "4789d0918e3c179069233416ae76449d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "leviathan-compose-jvm-3.1.0-1.8.2-sources.jar",
          "url": "leviathan-compose-jvm-3.1.0-1.8.2-sources.jar",
          "size": 1588,
          "sha512": "23de181f020f834e30f9f92191bd6cf9a8c91c47e5ff9948eb49edce313619fabe2575ed7a89ad5a230266a82806d5c70f81f1ebe8348af7102be89bbe53e17d",
          "sha256": "91f55d91e3ceb57b6e26300fa395098ff97ea9f7a84891926839837cd4240836",
          "sha1": "6b47ed0560ba0597dbb81460f1e66bf28926caa7",
          "md5": "97f546b54d1656117b8189160667ff39"
        }
      ]
    }
  ]
}
