{
  "formatVersion": "1.1",
  "component": {
    "url": "../../leviathan/3.1.0-1.8.2/leviathan-3.1.0-1.8.2.module",
    "group": "io.github.composegears",
    "module": "leviathan",
    "version": "3.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan.aar",
          "url": "leviathan-android-3.1.0-1.8.2.aar",
          "size": 13108,
          "sha512": "1314323ae77e08c9c767e923317cccc09780fb31d93a13cacdf7c44280dc0786b1c1871936d34b44a511160cd0d01535aec51b4259a06d987820aa662e69300a",
          "sha256": "98f2367ea43994c7ba7193b3d319c853c3beea99521bcf8277a3484c91b73cba",
          "sha1": "2d5083a483472a7e1d71d34e38b95382ac1e0ae9",
          "md5": "f3b6c769efab103a1ddc9d3e2cef1ef8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan.aar",
          "url": "leviathan-android-3.1.0-1.8.2.aar",
          "size": 13108,
          "sha512": "1314323ae77e08c9c767e923317cccc09780fb31d93a13cacdf7c44280dc0786b1c1871936d34b44a511160cd0d01535aec51b4259a06d987820aa662e69300a",
          "sha256": "98f2367ea43994c7ba7193b3d319c853c3beea99521bcf8277a3484c91b73cba",
          "sha1": "2d5083a483472a7e1d71d34e38b95382ac1e0ae9",
          "md5": "f3b6c769efab103a1ddc9d3e2cef1ef8"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "leviathan-android-3.1.0-1.8.2-sources.jar",
          "url": "leviathan-android-3.1.0-1.8.2-sources.jar",
          "size": 2790,
          "sha512": "1303aadf798b6073ff218b7266da7912708b3372d3a4582915a3e239a039dbccd3cbb74ec5a58d30002999dd7ec1a12826b22e8967fc0496e3fa9a3f6ec62519",
          "sha256": "bf95d41c29ef7307f7832a581d2eb65f4cf604b3fb29ac911641dafc5d763759",
          "sha1": "43e1dbead9322d5b23848d7a555f38c0c3487a75",
          "md5": "ed495bed930834c8335c5a372daefdd3"
        }
      ]
    }
  ]
}
