name: Build plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build signed plugin
        run: ./gradlew signPlugin

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: plugin/build/distributions/*.zip
