name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    env:
      CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

    outputs:
      version: ${{ steps.properties.outputs.artifactName }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup properties
        id: properties
        shell: bash
        run: |
          NAME=$(grep "^pluginName=" plugin.properties | cut -d '=' -f 2)
          VERSION=$(grep "^version=" plugin.properties | cut -d '=' -f 2)
          
          echo "NAME=$NAME"
          echo "VERSION=$VERSION"

          echo "name=$NAME" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "artifactName=$NAME-$VERSION" >> $GITHUB_ENV

      - name: Build signed plugin
        run: ./gradlew signPlugin

      - name: Verify IntelliJ plugin
        # https://www.jetbrains.com/idea/download/other.html
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          plugin-location: plugin/build/distributions/*-signed.zip
          ide-versions: |
            ideaIC:2024.1
            ideaIC:2024.1.1
            ideaIC:2024.1.2
            ideaIC:2024.1.3
            ideaIC:2024.1.4
            ideaIC:LATEST-EAP-SNAPSHOT
          failure-levels: |
            COMPATIBILITY_WARNINGS
            COMPATIBILITY_PROBLEMS
            DEPRECATED_API_USAGES
            INTERNAL_API_USAGES
            OVERRIDE_ONLY_API_USAGES
            NON_EXTENDABLE_API_USAGES
            PLUGIN_STRUCTURE_WARNINGS
            MISSING_DEPENDENCIES
            INVALID_PLUGIN
            NOT_DYNAMIC

      - name: Remove old drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      - name: Create draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.artifactName }} \
            --draft \
            --title "${{ env.artifactName }}" \
            --notes ""

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.artifactName }} ./plugin/build/distributions/*-signed.zip
