name: Deploy signed plugin into Jetbrains Marketplace

on:
  release:
    types: [created]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
      PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup properties
        id: properties
        shell: bash
        run: |
          NAME=$(grep "^pluginName=" plugin.properties | cut -d '=' -f 2)
          VERSION=$(grep "^version=" plugin.properties | cut -d '=' -f 2)
          
          echo "NAME=$NAME"
          echo "VERSION=$VERSION"

          echo "name=$NAME" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "artifactName=$NAME-$VERSION" >> $GITHUB_ENV

      - name: Build signed plugin
        run: ./gradlew publishPlugin
