name: Validation

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          config_file: .github/.linkspector.yml
          reporter: github-pr-check
          filter_mode: nofilter
          fail_level: any

  check-compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-java

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Check version compatibility
        run: ./gradlew :tools:idea-plugin:checkVersionCompatibility

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-java

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Run build
        run: ./gradlew build
