{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.composegears",
    "module": "leviathan-compose",
    "version": "3.1.0-1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.composegears",
          "module": "leviathan",
          "version": {
            "requires": "3.1.0-1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "leviathan-compose-metadata-3.1.0-1.8.2.jar",
          "url": "leviathan-compose-3.1.0-1.8.2.jar",
          "size": 2739,
          "sha512": "a4ad345f78669199e1196aa2bb04970e862d2f8d808704b54caf9ed4594e57ab5c87f480fc46c870ff2884b632557602017520aa261ccbc9b07c789afd65d656",
          "sha256": "282ac1e8e417816f4d30491064cdeb133b082bbfa8a29e9d34ae0f9d044f7b86",
          "sha1": "d8ed67a9899d4dd4e7575104a5374314b412137b",
          "md5": "07c9e3a2415835f10ae48ca0c4007bc5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "leviathan-compose-kotlin-3.1.0-1.8.2-sources.jar",
          "url": "leviathan-compose-3.1.0-1.8.2-sources.jar",
          "size": 1588,
          "sha512": "23de181f020f834e30f9f92191bd6cf9a8c91c47e5ff9948eb49edce313619fabe2575ed7a89ad5a230266a82806d5c70f81f1ebe8348af7102be89bbe53e17d",
          "sha256": "91f55d91e3ceb57b6e26300fa395098ff97ea9f7a84891926839837cd4240836",
          "sha1": "6b47ed0560ba0597dbb81460f1e66bf28926caa7",
          "md5": "97f546b54d1656117b8189160667ff39"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../leviathan-compose-android/3.1.0-1.8.2/leviathan-compose-android-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-android",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../leviathan-compose-android/3.1.0-1.8.2/leviathan-compose-android-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-android",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../leviathan-compose-android/3.1.0-1.8.2/leviathan-compose-android-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-android",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosarm64/3.1.0-1.8.2/leviathan-compose-iosarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosarm64/3.1.0-1.8.2/leviathan-compose-iosarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosarm64/3.1.0-1.8.2/leviathan-compose-iosarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosarm64/3.1.0-1.8.2/leviathan-compose-iosarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iossimulatorarm64/3.1.0-1.8.2/leviathan-compose-iossimulatorarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iossimulatorarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iossimulatorarm64/3.1.0-1.8.2/leviathan-compose-iossimulatorarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iossimulatorarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iossimulatorarm64/3.1.0-1.8.2/leviathan-compose-iossimulatorarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iossimulatorarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iossimulatorarm64/3.1.0-1.8.2/leviathan-compose-iossimulatorarm64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iossimulatorarm64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosx64/3.1.0-1.8.2/leviathan-compose-iosx64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosx64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosx64/3.1.0-1.8.2/leviathan-compose-iosx64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosx64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosx64/3.1.0-1.8.2/leviathan-compose-iosx64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosx64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../leviathan-compose-iosx64/3.1.0-1.8.2/leviathan-compose-iosx64-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-iosx64",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../leviathan-compose-jvm/3.1.0-1.8.2/leviathan-compose-jvm-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-jvm",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../leviathan-compose-jvm/3.1.0-1.8.2/leviathan-compose-jvm-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-jvm",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../leviathan-compose-jvm/3.1.0-1.8.2/leviathan-compose-jvm-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-jvm",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../leviathan-compose-wasm-js/3.1.0-1.8.2/leviathan-compose-wasm-js-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-wasm-js",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../leviathan-compose-wasm-js/3.1.0-1.8.2/leviathan-compose-wasm-js-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-wasm-js",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../leviathan-compose-wasm-js/3.1.0-1.8.2/leviathan-compose-wasm-js-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-wasm-js",
        "version": "3.1.0-1.8.2"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../leviathan-compose-wasm-js/3.1.0-1.8.2/leviathan-compose-wasm-js-3.1.0-1.8.2.module",
        "group": "io.github.composegears",
        "module": "leviathan-compose-wasm-js",
        "version": "3.1.0-1.8.2"
      }
    }
  ]
}
