settings.about.sourcecode=Source code
settings.about.issue=Submit issue or idea
settings.export.output.header=Output format
settings.export.output.backing=Backing property
settings.export.output.lazy=Lazy delegate property
settings.export.flat.package=Use flat package
settings.export.flat.package.description=Export all ImageVector icons into a single package without dividing by nested pack folders
settings.export.explicit.mode=Handle Kotlin explicit mode
settings.export.explicit.mode.description=Generate ImageVector icons and IconPack with explicit 'public' modifier
settings.export.trailing.comma=Add trailing comma
settings.export.trailing.comma.description=Insert a comma after the last element of ImageVector.Builder block and path params
settings.export.preview.block=Add @Preview annotation
settings.export.preview.block.description=Note: This option is deprecated. Consider using the built-in ImageVector previewer instead
settings.export.indent=Indent size
settings.export.indent.description=Determines the number of spaces used for each level of indentation in the exported icon
